# Site settings
title: Luftdaten.info aus Stuttgart
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Wir entwickeln Feinstaubmessgeräte und verteilen sie über die
  Stadt Stuttgart.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://luftdaten.info" # the base hostname & protocol for your site
twitter_username: codeforS
github_username: opendata-stuttgart

# Build settings
markdown: kramdown
