# Site settings
title: Luftdaten.info aus Stuttgart
email: your-email@domain.com
description.de: > # this means to ignore newlines until "description.en:"
  Wir entwickeln Feinstaubmessger채te und verteilen sie 체ber die
  Stadt Stuttgart.
description.en: > # this means to ignore newlines until "baseurl:"
  Wir entwickeln Feinstaubmessger채te und verteilen sie 체ber die
  Stadt Stuttgart.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://luftdaten.info" # the base hostname & protocol for your site
twitter_username: codeforS
github_username: opendata-stuttgart

# Build settings
markdown: kramdown
